### PR TITLE
add typedefs

### PR DESCRIPTION
**Pull request by 0xch4z**

### CODE REVIEW

**Comment by dmiller9911** [comment]
Is the plan to commit these back into the upstream project? These definitely seem useful for others.

**Review by dmiller9911 — APPROVED** [review]

**Comment by mdlavin** [comment]
> Is the plan to commit these back into the upstream project? These definitely seem useful for others.

I hope the plan is to push all of the changes we find useful upstream. I'm happy to do the work of getting the fixes accepted if it's not something others enjoy doing

**Comment by mdlavin** [comment]
I don't have enough experience to know if the types are correct. I'm going to assume that you got the types  from somewhere else on the web. It seems harmless to merge and see how it they work in practice

**Review by mdlavin — APPROVED** [review]

**Comment by 0xch4z** [comment]
@mdlavin They already have an open PR for TS definitions, this was partially sourced from that with a little tweaking. They said they want testing before they merge. I can do this at some point, I'm just trying to hurry this up.

**Pull request merged**
